<!DOCTYPE html>
<html>  
    <head>
        <title>Đồ án cuối kỳ</title>
        <link rel="shortcut icon" href="<?php echo $this->baseUrl() . "/"; ?>logo">
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/bootstrap.css>
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/carousel.css>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>

    </head>  
    <body class="bg">
        <br>
        <div class="container">
            <!-- Carousel ================================================== -->
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <img data-src="holder.js/900x500/auto/#777:#7a7a7a/text:First slide" alt="First slide">
                        <img src="<?php echo $this->baseUrl() . "/"; ?>upload/product/namecard/Photographer_Business_Card.jpg" alt="First slide">
                        <div class="container">
                            <div class="carousel-caption">
                                <h2 style="color: lightskyblue;">Công ty TNHH in XXX</h2>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <img data-src="holder.js/900x500/auto/#666:#6a6a6a/text:Second slide" alt="Second slide">
                        <img src="<?php echo $this->baseUrl() . "/"; ?>upload/product/thiep/wedding-invite-tree.jpg" alt="Second slide">
                        <div class="container">
                            <div class="carousel-caption">
                                <h2 style="color: lightskyblue;">Chuyên nhận in các loại Thiệp, NameCard, Catalogue,...</h2>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <img data-src="holder.js/900x500/auto/#555:#5a5a5a/text:Third slide" alt="Third slide">
                        <img src="<?php echo $this->baseUrl() . "/"; ?>upload/product/catalogue/brochure5.jpg" alt="Third slide">
                        <div class="container">
                            <div class="carousel-caption">
                                <h2 style="color: lightskyblue;">Chất lượng cao, mẫu mã đa dạng, thiết kế theo yêu cầu</h2>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
            </div>
            <!-- /.carousel -->

            <?php echo $this->layout()->content; ?>
            <br>
            <footer>
                <div class="row">
                    <div class="span4">
                        <h4 class="muted text-center">Về Đối tác</h4>
                        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                        <a href="#" class="btn"><i class="icon-user"></i> Khách hàng của chúng tôi</a>
                    </div>
                    <div class="span4">
                        <h4 class="muted text-center">Về Đội ngũ</h4>
                        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                        <a href="#" class="btn btn-success"><i class="icon-star icon-white"></i> Đội ngũ của chúng tôi</a>
                    </div>
                    <div class="span4">
                        <h4 class="muted text-center">Về Giải Thưởng</h4>
                        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                        <a href="#" class="btn btn-info">Liên hệ với chúng tôi</a>
                    </div>
                </div>
            </footer>
        </div>
        <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
        <script src=<?php echo $this->baseUrl() . "/"; ?>js/bootstrap.js></script>
        <script src=<?php echo $this->baseUrl() . "/"; ?>js/bootstrap-hover-dropdown.js></script>
        <script src=<?php echo $this->baseUrl() . "/"; ?>js/holder.js></script>
    </body> 
</html>