<!DOCTYPE html>
<html>  
    <head>
        <title>Đồ án cuối kỳ</title>
        <link rel="shortcut icon" href="<?php echo $this->baseUrl() . "/"; ?>logo">
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/bootstrap.css>
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/carousel.css>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>

    </head>  
    <body class="bg">

        <div class="container">
            <!-- Carousel ================================================== -->
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <img data-src="holder.js/900x500/auto/#777:#7a7a7a/text:First slide" alt="First slide">
                        <div class="container">
                            <div class="carousel-caption">

                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <img data-src="holder.js/900x500/auto/#666:#6a6a6a/text:Second slide" alt="Second slide">
                        <div class="container">
                            <div class="carousel-caption">

                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <img src="<?php echo $this->baseUrl() . "/"; ?>upload/image/MAU_1.jpg" alt="Third slide">
                        <div class="container">
                            <div class="carousel-caption">
                                <a>fsdafsafsdfsd</a>
                                <br>
                                <a>fsdafsafsdfsd</a>
                                <a>fsdafsafsdfsd</a>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
            </div>
            <!-- /.carousel -->


            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <ul class="nav">
                            <div class="btn-group">
                                <button class="btn dropdown-menu" onclick="location.href=<?php echo $this->baseUrl() . "/"; ?>;"><i class="icon-home"></i> Trang chủ <span ></span></button>
                            </div>
                            <div class="btn-group">
                                <button data-toggle="dropdown" data-hover="dropdown" class="btn dropdown-toggle"><i class="icon-ok-circle"></i> Giới thiệu <span class="caret"></span></button>
                                <ul class="dropdown-menu bg">
                                    <li><a href="#">Về đề tài</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Về nhóm 08</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Về môn học</a></li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <button data-toggle="dropdown" data-hover="dropdown" class="btn dropdown-toggle"><i class="icon-time"></i> Sản Phẩm <span class="caret"></span></button>
                                <ul class="dropdown-menu bg">
                                    <li><a href="#">Thiệp cưới</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Lịch</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Catalogue</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Name card</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Tờ rơi</a></li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <button data-toggle="dropdown" class="btn dropdown-toggle" onclick="location.href=<?php echo $this->baseUrl() . "/"; ?>;"><i class="icon-trash"></i>Dịch vụ khác</button>
                            </div>
                            <div class="btn-group">
                                <button data-toggle="dropdown" class="btn dropdown-toggle" onclick="location.href=<?php echo $this->baseUrl() . "/"; ?>;"><i class="icon-shopping-cart"></i> Liên hệ </button>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
            <article class="row">
                <section class="span22">
                    <ul class="nav nav-list bg-list">
                        <li class="nav-header bg-menu-title" align="center"><h6 style="color: black;">Số lượt truy cập</h6></li>
                        <li align="center"><h1><img src="http://cc.amazingcounters.com/counter.php?i=3153335&c=9460318"></h1></li>
                        <li class="divider"></li>
                        <li class="nav-header bg-menu-title" align="center"><h6 style="color: black;">Danh mục sản phẩm</h6></li>
                        <li class="active"><a href="#">Thiệp cưới</a></li>
                        <li><a href="#">Lịch</a></li>
                        <li><a href="#">Catalogue</a></li>
                        <li><a href="#">Name card</a></li>
                        <li><a href="#">Tờ rơi</a></li>
                        <li class="divider"></li>
                        <li class="nav-header bg-menu-title" align="center"><h6 style="color: black;">Hỗ trợ trực tuyến!</h6></li>
                        <li>
                            <a href="ymsgr:sendIM?yeuem1000nam_1991">Lê Phước Thạch</a>
                            <a href="ymsgr:sendIM?yeuem1000nam_1991">
                                <img src="http://opi.yahoo.com/online?u=yeuem1000nam_1991&t=14">
                            </a>
                        </li>
                        <li>
                            <a href="ymsgr:sendIM?visaoemoi_03tk">Nguyễn Văn Chiến</a>
                            <a href="ymsgr:sendIM?visaoemoi_03tk">
                                <img src="http://opi.yahoo.com/online?u=visaoemoi_03tk&t=14">
                            </a>
                        </li>
                        <li>
                            <a href="ymsgr:sendIM?kimcuongcatkimcuong_12">Lâm Văn Quốc Huy</a>
                            <a href="ymsgr:sendIM?kimcuongcatkimcuong_12">
                                <img src="http://opi.yahoo.com/online?u=yeuem1000nam_1991&t=14">
                            </a>
                        </li>
                    </ul>
                </section>
                <section>
                    <?php echo $this->layout()->content; ?>
                </section>
            </article>
            <footer>
                <div class="row">
                    <div class="span4">
                        <h4 class="muted text-center">Về Đối tác</h4>
                        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                        <a href="#" class="btn"><i class="icon-user"></i> Khách hàng của chúng tôi</a>
                    </div>
                    <div class="span4">
                        <h4 class="muted text-center">Về Đội ngũ</h4>
                        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                        <a href="#" class="btn btn-success"><i class="icon-star icon-white"></i> Đội ngũ của chúng tôi</a>
                    </div>
                    <div class="span4">
                        <h4 class="muted text-center">Về Giải Thưởng</h4>
                        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                        <a href="#" class="btn btn-info">Liên hệ với chúng tôi</a>
                    </div>


                </div>
                <hr>
                <div class="footer text-left">
                    <h2>Nhóm 08</h2>
                </div>
            </footer>
        </div>
        <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
        <script src=<?php echo $this->baseUrl() . "/"; ?>js/bootstrap.js></script>
        <script src=<?php echo $this->baseUrl() . "/"; ?>js/bootstrap-hover-dropdown.js></script>
    </body> 
</html>