<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body style="">
        <div class="container">          
            <article class="row">
                <section class="span8">
                    <h3 align="center">CNWeb&UD - SE322.E12 - NHÓM 08</h3>
                    <br>
                    <h5>
                        <a>Lê Phước Thạch</a>
                        <a href="ymsgr:sendIM?yeuem1000nam_1991">
                            <img src="http://opi.yahoo.com/online?u=yeuem1000nam_1991&t=02">
                        </a>
                        <br>
                        <a>MSSV: 10520204</a>
                        <br>
                        <a>SĐT: 01655381053</a>
                        <br>
                        <a>Email: lephuocthach@gmail.com</a>
                    </h5>
                    <br>
                    <h5>
                        <a href="ymsgr:sendIM?visaoemoi_03tk">Nguyễn Văn Chiến</a>
                        <a href="ymsgr:sendIM?visaoemoi_03tk">
                            <img src="http://opi.yahoo.com/online?u=visaoemoi_03tk&t=02">
                        </a>
                        <br>
                        <a>MSSV: 10520112</a>
                        <br>
                        <a>SĐT: 01696210037</a>
                        <br>
                        <a>Email: Smalldeviltk@gmail.com</a>
                    </h5>
                    <br>
                    <h5>
                        <a href="ymsgr:sendIM?kimcuongcatkimcuong_12">Lâm Văn Quốc Huy</a>
                        <a href="ymsgr:sendIM?kimcuongcatkimcuong_12">
                            <img src="http://opi.yahoo.com/online?u=yeuem1000nam_1991&t=02">
                        </a>
                        <br>
                        <a>MSSV: 10520113</a>
                        <br>
                        <a>SĐT: 0983122020</a>
                        <br>
                        <a>Email: lvqh12@gmail.com</a>
                    </h5>
                </section>
            </article>
        </div>

    </body>
</html>