<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body style="">
        <div class="container">
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <ul class="nav">
                            <div class="btn-group">
                                <a class="btn dropdown-menu" href ="<?php echo $this->baseUrl() . "/"; ?>" style="font-weight: bold;"><i class="icon-home"></i> Trang chủ <span ></span></a>
                            </div>
                            <div class="btn-group">
                                <a data-toggle="dropdown" data-hover="dropdown" class="btn dropdown-toggle" style="font-weight: bold;"><i class="icon-ok"></i> Giới thiệu <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->baseUrl() . "/about" ?>">Về đề tài</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>contact">Về nhóm 08</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Về môn học</a></li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <a  data-hover="dropdown" class="btn dropdown-toggle" style="font-weight: bold;"><i class="icon-gift "></i> Sản Phẩm <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>thiep">Thiệp</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>lich">Lịch</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>catalogue">Catalogue</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>namecard">Name card</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>toroi">Tờ rơi</a></li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <a class="btn" href ="<?php echo $this->baseUrl() . "/otherservices" ?>" style="font-weight: bold;"><i class="icon-list"></i> Dịch vụ khác</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn" href ="<?php echo $this->baseUrl() . "/contact" ?>" style="font-weight: bold;"><i class="icon-user"></i> Liên hệ </a>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="navbar-inner">
                <article class="row">
                    <section class="span22">
                        <ul class="nav nav-list bg-list">
                            <li class="nav-header bg-menu-title" align="center"><h6 style="color: black;">Số lượt truy cập</h6></li>
                            <li align="center"><h1><img src="http://cc.amazingcounters.com/counter.php?i=3153335&c=9460318"></h1></li>
                            <li class="nav-header bg-menu-title" align="center"><h6 style="color: black;">Danh mục sản phẩm</h6></li>
                            <li><a href="<?php echo $this->baseUrl() . "/"; ?>thiep"> Thiệp</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/"; ?>lich"> Lịch</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/"; ?>catalogue"> Catalogue</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/"; ?>namecard"> Name card</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/"; ?>toroi"> Tờ rơi</a></li>
                            <li class="nav-header bg-menu-title" align="center"><h6 style="color: black;">Hỗ trợ trực tuyến!</h6></li>
                            <li>
                                <a href="ymsgr:sendIM?yeuem1000nam_1991">Lê Phước Thạch</a>
                                <a href="ymsgr:sendIM?yeuem1000nam_1991">
                                    <img src="http://opi.yahoo.com/online?u=yeuem1000nam_1991&t=14">
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="ymsgr:sendIM?visaoemoi_03tk">Nguyễn Văn Chiến</a>
                                <a href="ymsgr:sendIM?visaoemoi_03tk">
                                    <img src="http://opi.yahoo.com/online?u=visaoemoi_03tk&t=14">
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="ymsgr:sendIM?kimcuongcatkimcuong_12">Lâm Văn Quốc Huy</a>
                                <a href="ymsgr:sendIM?kimcuongcatkimcuong_12">
                                    <img src="http://opi.yahoo.com/online?u=kimcuongcatkimcuong_12&t=14">
                                </a>
                            </li>
                        </ul>
                    </section>
                    <section class="span8">
                        <h3 align = "center">CNWeb&UD - SE322.E12 - NHÓM 08</h3>
                        <br>
                        <h6>Cảm ơn bạn đã ủng hộ chúng tôi. Nếu có thắc mắc hay muốn đặt đơn hàng, bạn có thể liên hệ trực tiếp với chúng tôi thông qua hỗ trợ trực tuyến hoặc để lại thông tin của bạn lại đây. Chúng tôi sẽ giải quyết và liên hệ lại với bạn sớm nhất có thể.</h6>
                        <h5>
                            <?php echo $this->formLienHe; ?>   
                            <a onclick="return confirm('Bạn có chắc chắn ko ?');" href="http://sinhvienit.net/"></a>
                        </h5>
                        
<!--                        <h5>
                            <a>Lê Phước Thạch</a>
                            <a href = "ymsgr:sendIM?yeuem1000nam_1991">
                                <img src = "http://opi.yahoo.com/online?u=yeuem1000nam_1991&t=02">
                            </a>
                            <br>
                            <a>MSSV: 10520204</a>
                            <br>
                            <a>SĐT: 01655381053</a>
                            <br>
                            <a>Email: lephuocthach@gmail.com</a>
                        </h5>
                        <br>
                        <h5>
                            <a href = "ymsgr:sendIM?visaoemoi_03tk">Nguyễn Văn Chiến</a>
                            <a href = "ymsgr:sendIM?visaoemoi_03tk">
                                <img src = "http://opi.yahoo.com/online?u=visaoemoi_03tk&t=02">
                            </a>
                            <br>
                            <a>MSSV: 10520112</a>
                            <br>
                            <a>SĐT: 01696210037</a>
                            <br>
                            <a>Email: Smalldeviltk@gmail.com</a>
                        </h5>
                        <br>
                        <h5>
                            <a href = "ymsgr:sendIM?kimcuongcatkimcuong_12">Lâm Văn Quốc Huy</a>
                            <a href = "ymsgr:sendIM?kimcuongcatkimcuong_12">
                                <img src = "http://opi.yahoo.com/online?u=kimcuongcatkimcuong_12&t=02">
                            </a>
                            <br>
                            <a>MSSV: 10520113</a>
                            <br>
                            <a>SĐT: 0983122020</a>
                            <br>
                            <a>Email: lvqh12@gmail.com</a>
                        </h5>-->
                    </section>
                </article>
            </div>
        </div>
    </body>
</html>





