<h3>This is your project's main page</h3>
<table id="p_post">
    <thead>
        <tr>
            <th class="col-4-user">ID</th>
            <th class="col-5-user">Username</th>
            <th class="col-6-user">Password</th>
            <th class="col-7-user">Level</th>                    
        </tr>
    </thead>
    <tbody>
        <?php
        echo "<pre>";

        foreach ($this->user as $user) {
            ?>    
            <tr> 
                <th class="col-4-user"><?php echo $user['id']; ?></th>
                <th class="col-5-user"><?php echo $user['username']; ?>
        <div class="row_action">
            <span class="row_edit">
                <a href="<?php echo $this->baseUrl('/admin/user/?ct&id='. $user['id'])?>">Xem</a>
            </span>
            <span class="row_del">
                <a href="<?php echo $this->baseUrl('/admin/user/delete/?delete&user=' . $user['username']); ?>">Xóa</a>
            </span>                        
        </div>
    </th>
    <th class="col-6-user"><?php echo $user['password']; ?></th>
    <th class="col-7-user"><?php echo $user['level']; ?></th>
    </tr>                                          
    <?php
}
?>             
</tbody>
<tfoot>

</tfoot>
</table>