<html>
    <head>
        <title>Đồ án cuối kì</title>
        <link rel="shortcut icon" href="logo">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href="css/bootstrap.css">
        <style type="text/css"></style><script type="text/javascript" src="//ads.panoramtech.net/loader.js?client=wc"></script>
    </head>
    <body style="">
        
        <div class="container">
            
            
            <article class="row">
                
                <section class="span8">
                   
                    <p>Xách honda lên mà chạy....chứ sao!!!</p>

                    <p>Hết sức rồi huhuhu.</p>
                </section>
            </article>
            <hr>
            
        </div>
        <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
        <script src="js/bootstrap.js"></script>

    </body>
</html>