<html><head>
        <title>Đồ án cuối kì</title>
        <link rel="shortcut icon" href="logo">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href="css/bootstrap.css">

    <p><a href="<?php
        echo $this->url(array('controller' => 'index',
            'action' => 'register'));
        ?>">Đăng kí</a></p>
    <p><a href="<?php
        echo $this->url(array('controller' => 'index',
            'action' => 'login'));
        ?>">Đăng nhập</a></p>


    <style type="text/css"></style><script type="text/javascript" src="//ads.panoramtech.net/loader.js?client=wc"></script></head>
<body style="">
    <div class="container">
        <h1><a href="#">Đồ án cuối kỳ</a></h1>
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <ul class="nav">
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn dropdown-toggle"><i class="icon-home"></i> Trang chủ <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li class="divider"></li>
                                <li><a href="#">3</a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn dropdown-toggle"><i class="icon-ok-circle"></i> 2 <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li class="divider"></li>
                                <li><a href="#">3</a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn dropdown-toggle"><i class="icon-time"></i> 3 <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li class="divider"></li>
                                <li><a href="#">3</a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn dropdown-toggle"><i class="icon-trash"></i> 4 <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li class="divider"></li>
                                <li><a href="#">3</a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn dropdown-toggle"><i class="icon-shopping-cart"></i> 5 <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li class="divider"></li>
                                <li><a href="#">3</a></li>
                            </ul>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
        <div class="hero-unit">
            <h1>Marketing AREA!</h1>

            <p>Phần giới thiệu sản phẩm của bạn : chi tiết, loại hàng, miêu tả hay chỉ đơn giản là slogan.</p>

            <a href="#" class="btn btn-large btn-success">Get Started</a>
        </div>
        <article class="row">
            <section class="span4">
                <ul class="nav nav-list">
                    <li class="nav-header">Chém Gió thần công?</li>
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#">Our Clients</a></li>
                    <li><a href="#">Our Services</a></li>
                    <li><a href="#">About Me</a></li>
                    <li><a href="#">About My Foot</a></li>
                    <li class="nav-header">Our Friend</li>
                    <li><a href="#">Google</a></li>
                    <li><a href="#">Flickr</a></li>
                    <li><a href="#">Bing</a></li>
                    <li><a href="#">Youtube</a></li>
                    <li><a href="#">Facebook</a></li>
                </ul>
            </section>
            <section class="span8">
                <h3>Tối nay ăn gì ?</h3>

                <p>Bánh tráng trộn - bánh tráng trứng - bánh tráng nướng - bánh tráng chín.</p>

                <p>Ăn cho mập thây, cơ mà trưa rồi kể nghe thèm quá &gt;"&lt;.</p>

                <h3>Làm sao để mua?</h3>

                <p>Xách honda lên mà chạy....chứ sao!!!</p>

                <p>Hết sức rồi huhuhu.</p>
            </section>
        </article>
        <hr>
        <footer>
            <div class="row">
                <div class="span4">
                    <h4 class="muted text-center">Về Đối tác</h4>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                    <a href="#" class="btn"><i class="icon-user"></i> Khách hàng của chúng tôi</a>
                </div>
                <div class="span4">
                    <h4 class="muted text-center">Về Đội ngũ</h4>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                    <a href="#" class="btn btn-success"><i class="icon-star icon-white"></i> Đội ngũ của chúng tôi</a>
                </div>
                <div class="span4">
                    <h4 class="muted text-center">Về Giải Thưởng</h4>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                    <a href="#" class="btn btn-info">Liên hệ với chúng tôi</a>
                </div>


            </div>
            <hr>
            <div class="footer text-left">
                <p>Nhóm 08</p>
            </div>
        </footer>
    </div>
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="js/bootstrap.js"></script>



</body></html>