<html>
    <head>
        <title>Đồ án cuối kì</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/detail.css>
    </head>
    <body style="">
        <div class="container">
            <article class="row">
                <section class="span9">
                    <div class="pro_box_big">
                        <?php
                        foreach ($this->detail as $detail) {
                            ?>    
                            <div class="item_product">
                                <div class="images"><a href="#"><img src="<?php echo $this->baseUrl() . "/"; ?>upload/image/<?php echo $detail['hinhanh']; ?>" border="0"></a></div>  
                                <div style="height:10px; width:100%;"></div>
                                <div class="name"><a href=""><?php echo $detail['tensanpham']; ?></a></div>       
                            </div>
                            <?php
                        }
                        ?>   
                        <div>
                            <a><?php echo $detail['tensanpham']; ?></a>
                            <a><?php echo $detail['tensanpham']; ?></a>
                            <a><?php echo $detail['tensanpham']; ?></a>
                            <a><?php echo $detail['tensanpham']; ?></a>
                        </div>
                    </div>
                    <p>MẪU 1:</p>
                    <p><img src="<?php echo $this->baseUrl() . "/"; ?>upload/image/<?php echo $detail['hinhanh']; ?>" alt="" width="700" height="486" /></p>
                </section>
            </article>
            <hr>

        </div>
    </body>
</html>