<?php
//dung chung cho tat ca
//nen de o ngoai tat ca cac thu muc thuoc views
if(isset($this->previous)){
	echo '<a href="'.$this->url(array('page'=>$this->first)).'">Trang đầu</a>';
	echo '<a href="'.$this->url(array('page'=>$this->previous)).'">< </a>';
}

foreach ($this->pagesInRange as $page) {
	if($this->current != $page){
		echo '<a href="'.$this->url(array('page' => $page)).'">'.$page."</a>";
	}else{
		echo '<a class="active-paginator">'.$page.'</a>';
	}
}

if(isset($this->next)){
	echo '<a href="'.$this->url(array('page'=>$this->next)).'">></a>';
	echo '<a href="'.$this->url(array('page'=>$this->last)).'">Trang cuối</a>';
}