<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body style="">        
        <div class="container">          
            <article class="row">
                <section class="span8">
                    <h3>Tối nay ăn gì ?</h3>

                    <p> Bánh tráng trộn - bánh tráng trứng - bánh tráng nướng - bánh tráng chín.</p>

                    <p>Ăn cho mập thây, cơ mà trưa rồi kể nghe thèm quá &gt;"&lt;.</p>

                    <h3>Làm sao để mua?</h3>

                    <p>Xách honda lên mà chạy....chứ sao!!!</p>

                    <p>Hết sức rồi huhuhu.</p>
                </section>
                <section>
                    <dl class="zend_form">
                        <dd>
                            <input type="file" name="file" id="file">
                        </dd>
                        <dt id="Upload-label">&nbsp;</dt>
                        <dd id="Upload-element">
                            <input type="submit" name="Upload" id="Upload" value="Upload">
                        </dd>
                    </dl>
                </section>
            </article>
        </div>
    </body>
</html>