<html>
    <head>
    <p>
        <a href="<?php
        echo $this->url(array('controller' => 'index',
            'action' => 'register'));
        ?>">Đăng kí</a>
    </p>
    <p>
        <a href="<?php
        echo $this->url(array('controller' => 'index',
            'action' => 'login'));
        ?>">Đăng nhập</a>
    </p>
</head>
<body style="">        
    <div class="container">          
        <article class="row">
            <section class="span8">
                <h3>Tối nay ăn gì ?</h3>

                <p>Bánh tráng trộn - bánh tráng trứng - bánh tráng nướng - bánh tráng chín.</p>

                <p>Ăn cho mập thây, cơ mà trưa rồi kể nghe thèm quá &gt;"&lt;.</p>

                <h3>Làm sao để mua?</h3>

                <p>Xách honda lên mà chạy....chứ sao!!!</p>

                <p>Hết sức rồi huhuhu.</p>
            </section>
        </article>
    </div>
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="js/bootstrap.js"></script>

</body>
</html>