<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<head>
    <TITLE>Nhóm 8 - default</TITLE>
    <LINK REL="SHORTCUT ICON" href="logo">
    <META http-equiv=Content-Type content="text/html; charset=UTF-8">
</head>
<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }

    img.expa {
        transition: all 5s;
        -webkit-transition: all 5s;
        -moz-transition: all 5s;
        -o-transition: all 5s;
    }

    img.expa:hover {
        transform: scale(1.5,1.5);
        -webkit-transform: scale(1.5,1.5);
        -moz-transform: scale(1.5,1.5);
        -o-transform: scale(1.5,1.5);
    }
</style>
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>

    <h3>This is your project's main page</h3>

    <div id="more-information">
        <p><img class="expa" src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
        <p>
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>
    </div>
</div>

<html>
    <body>
        <p>
            Demo 3 kỹ thuật
        </p>

        <!-- Zoom ảnh-->
        <!---------------------------------------------------------------------------------------------------->

        <div align="center">
            <a>Zoom ảnh</a>
            <br>
            <img class="expa" src="http://bp.uuuploads.com/paper-art/paper-art-7-4.jpg" />

        </div>

        <br>
        <div align="center">-------------------------------------------------------------------------------------------------------------</div>
        <br>

        <!-- Đếm số lượt truy cập-->
        <!---------------------------------------------------------------------------------------------------->

        <div align="center">
            <a href="http://facebook.com">
                <a>Số lượt truy cập</a>
                <br>
                <img src="http://cc.amazingcounters.com/counter.php?i=3153335&c=9460318">
            </a>
        </div>

        <br>
        <div align="center">-------------------------------------------------------------------------------------------------------------</div>
        <br>

        <!-- Link kết tới yahoo-->
        <!---------------------------------------------------------------------------------------------------->
        <div align="center">
            <a>Yahoo of Smalldevil</a>
            <br>
            <a href="ymsgr:sendIM?visaoemoi_03tk">
                <img src="http://opi.yahoo.com/online?u=visaoemoi_03tk&t=14">
            </a>
        </div>
    </body>
</html>