<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body style="">
        <div class="container">
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <ul class="nav">
                            <div class="btn-group">
                                <a class="btn dropdown-menu" href ="<?php echo $this->baseUrl() . "/" ?>" style="font-weight: bold;"><i class="icon-home"></i> Trang chủ <span ></span></a>
                            </div>
                            <div class="btn-group">
                                <a data-toggle="dropdown" data-hover="dropdown" class="btn dropdown-toggle" style="font-weight: bold;"><i class="icon-ok"></i> Giới thiệu <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->baseUrl() . "/about" ?>">Về đề tài</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>contact">Về nhóm 08</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Về môn học</a></li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <a  data-hover="dropdown" class="btn dropdown-toggle" style="font-weight: bold;"><i class="icon-gift "></i> Sản Phẩm <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>thiep">Thiệp</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>lich">Lịch</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>catalogue">Catalogue</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>namecard">Name card</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>toroi">Tờ rơi</a></li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <a class="btn" href ="<?php echo $this->baseUrl() . "/otherservices" ?>" style="font-weight: bold;"><i class="icon-list"></i> Dịch vụ khác</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn" href ="<?php echo $this->baseUrl() . "/contact" ?>" style="font-weight: bold;"><i class="icon-user"></i> Liên hệ </a>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="navbar-inner">
                <article class="row">
                    <section class="span22">
                        <ul class="nav nav-list bg-list">
                            <li class="nav-header bg-menu-title" align="center"><h6 style="color: black;">Quản lý sản phẩm</h6></li>
                            <li class="active"><a href="<?php echo $this->baseUrl() . "/admin/"; ?>thiep">Thiệp</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/admin/"; ?>lich">Lịch</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/admin/"; ?>catalogue">Catalogue</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/admin/"; ?>namecard">Name card</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/admin/"; ?>toroi">Tờ rơi</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/admin/"; ?>user">User</a></li>
                            <li class="nav-header bg-menu-title" align="center"><h6 style="color: black;">Hình ảnh!</h6></li>
                            <li><a href="<?php echo $this->baseUrl() . "/admin/"; ?>upload">Upload ảnh</a></li>
                            <li class="divider"></li>
                        </ul>
                    </section>
                    <br>
                    <a class="pull-right" href ="<?php echo $this->baseUrl() . "/admin/thiep/" ?>add" style="font-weight: bold;"> Thêm sản phẩm </a>
                    <br>
                    <center>
                        <h3>Thiệp</h3>
                        <section class="span8">               
                            <?php if ($this->data != null) { ?>
                                <table id="p_post" border="1">
                                    <thead>
                                        <tr>
                                            <th class="col-4-user">Mã</th>
                                            <th class="col-5-user">Tên sản phẩm</th>
                                            <th class="col-6-user">Thông tin</th>
                                            <th class="col-7-user">Giá</th> 
                                            <th class="col-3-user">Hình ảnh</th> 
                                            <th class="col-3-user">Control</th> 
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        foreach ($this->data as $user) {
                                            ?>    
                                            <tr> 
                                                <th class="col-4-user"><?php echo $user['masanpham']; ?></th>
                                                <th class="col-5-user"><?php echo $user['tensanpham']; ?>
                                                </th>
                                                <th width="300" style="display:block; overflow:scroll" class="col-6-user"><?php echo $user['thongtin']; ?></th>
                                                <th class="col-7-user"><?php echo $user['gia']; ?></th>
                                                <th class="col-7-user"><?php echo $user['hinhanh']; ?></th>
                                                <th>
                                        <div class="row_action">
                                            <span class="row_edit">
                                                <a href="<?php echo $this->baseUrl('/admin/thiep/add?edit&id=' . $user['id']) ?>">Sửa</a>
                                            </span>
                                            <span class="row_del">
                                                <a href="<?php echo $this->baseUrl('/admin/thiep/delete/?del&id=' . $user['id']); ?>">Xóa</a>
                                            </span>                        
                                        </div>
                                        </th>
                                        </tr>                                          
                                        <?php
                                    }
                                    ?>             
                                    </tbody>
                                </table>
                                <center>
                                    <?php
                                    echo $this->paginationControl($this->data, 'Sliding', 'paginator.phtml');
                                    ?>
                                </center>
                                <?php
                            } else {
                                echo 'No products';
                            }
                            ?>
                        </section>
                    </center>
                </article>
            </div>
        </div>
    </body>
</html>
