<!DOCTYPE html>
<html>  
    <head>
        <title>Đồ án cuối kỳ</title>
        <link rel="shortcut icon" href="<?php echo $this->baseUrl() . "/"; ?>logo">
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/bootstrap.css>
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/carousel.css>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
    </head>  
    <body>
        <p></p>
        <div class="container">
            <div class="header ui-corner-all">			
                <div class="hero-unit">
                    <img src="<?php echo $this->baseUrl() . "/"; ?>img/MAU_81.jpg"/>
                </div>
            </div>
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <ul class="nav">
                            <div class="btn-group">
                                <button class="btn dropdown-menu"><i class="icon-home"></i> Trang chủ <span ></span></button>
                            </div>
                            <div class="btn-group">
                                <button data-toggle="dropdown" data-hover="dropdown" class="btn dropdown-toggle"><i class="icon-ok-circle"></i> Giới thiệu <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Về đề tài</a></li>
                                    <li><a href="#">Về nhóm 08</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Về môn học</a></li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <button data-toggle="dropdown" data-hover="dropdown" class="btn dropdown-toggle"><i class="icon-time"></i> Sản Phẩm <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Thiệp cưới</a></li>
                                    <li><a href="#">Lịch</a></li>
                                    <li><a href="#">Catalogue</a></li>
                                    <li><a href="#">Name card</a></li>
                                    <li><a href="#">Tờ rơi</a></li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <button data-toggle="dropdown" class="btn dropdown-toggle"><i class="icon-trash"></i>Dịch vụ khác</button>
                            </div>
                            <div class="btn-group">
                                <button data-toggle="dropdown" class="btn dropdown-toggle"><i class="icon-shopping-cart"></i> Liên hệ </button>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
            <article class="row">
                <section class="span22">
                    <ul class="nav nav-list">
                        <li class="nav-header">Danh mục sản phẩm</li>
                        <li class="active"><a href="#">Thiệp cưới</a></li>
                        <li><a href="#">Lịch</a></li>
                        <li><a href="#">Catalogue</a></li>
                        <li><a href="#">Name card</a></li>
                        <li><a href="#">Tờ rơi</a></li>
                        <li class="nav-header">Hỗ trợ trực tuyến!</li>
                        <li><a href="#">Google</a></li>
                        <li><a href="#">Flickr</a></li>
                        <li><a href="#">Bing</a></li>
                        <li><a href="#">Youtube</a></li>
                        <li><a href="#">Facebook</a></li>
                    </ul>
                </section>
                <section>
                    <?php echo $this->layout()->content; ?>
                </section>
            </article>
            <footer>
                <div class="row">
                    <div class="span4">
                        <h4 class="muted text-center">Về Đối tác</h4>
                        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                        <a href="#" class="btn"><i class="icon-user"></i> Khách hàng của chúng tôi</a>
                    </div>
                    <div class="span4">
                        <h4 class="muted text-center">Về Đội ngũ</h4>
                        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                        <a href="#" class="btn btn-success"><i class="icon-star icon-white"></i> Đội ngũ của chúng tôi</a>
                    </div>
                    <div class="span4">
                        <h4 class="muted text-center">Về Giải Thưởng</h4>
                        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                        <a href="#" class="btn btn-info">Liên hệ với chúng tôi</a>
                    </div>


                </div>
                <hr>
                <div class="footer text-left">
                    <h1>Nhóm 08</h1>
                </div>
            </footer>
        </div>
        <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
        <script src=<?php echo $this->baseUrl() . "/"; ?>js/bootstrap.js></script>
        <script src=<?php echo $this->baseUrl() . "/"; ?>js/bootstrap-hover-dropdown.js></script>
    </body> 
</html>