<!DOCTYPE html>
<html>  
    <head>
        <title>Đồ án cuối kỳ</title>
        <link rel="shortcut icon" href="<?php echo $this->baseUrl() . "/"; ?>logo">
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/bootstrap.css>
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/carousel.css>
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/style.css>
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/centercontent.css>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>

    </head>  
    <body>
        <div class ="main">
                <!--- TOP START --->
                <div class ="top">
                    <!-- Carousel
            ================================================== -->
                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel" data-slide-to="1"></li>
                            <li data-target="#myCarousel" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img data-src="holder.js/900x500/auto/#777:#7a7a7a/text:First slide" alt="First slide">
                                <div class="container">
                                    <div class="carousel-caption">

                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <img data-src="holder.js/900x500/auto/#666:#6a6a6a/text:Second slide" alt="Second slide">
                                <div class="container">
                                    <div class="carousel-caption">

                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <img src="<?php echo $this->baseUrl() . "/"; ?>upload/image/MAU_1.jpg" alt="Third slide">
                                <div class="container">
                                    <div class="carousel-caption">
                                        <a>fsdafsafsdfsd</a>
                                        <br>
                                        <a>fsdafsafsdfsd</a>
                                        <a>fsdafsafsdfsd</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
                    </div><!-- /.carousel -->
                </div>
                <!--- TOP END --->
                <div class ="clr"></div>

                    <!--                    <article class="row">-->
                    <div class="left_content">
                        <div class ="title_box">Danh mục sản phẩm</div>
                        <ul class="left_menu">
                        </ul>
                        <div class ="title_box">Hỗ trợ trực tuyến</div>
                        <ul class="left_menu">
                            
                            <li class ="odd"><a href="#">xxxx</a></li>
                        </ul>
                        <!--                            <ul class="nav nav-list">
                                                        <li class="nav-header">Danh mục sản phẩm</li>
                                                        <li class="active"><a href="#">Thiệp cưới</a></li>
                                                        <li><a href="#">Lịch</a></li>
                                                        <li><a href="#">Catalogue</a></li>
                                                        <li><a href="#">Name card</a></li>
                                                        <li><a href="#">Tờ rơi</a></li>
                                                        <li class="nav-header">Hỗ trợ trực tuyến!</li>
                                                        <li><a href="#">Google</a></li>
                                                        <li><a href="#">Flickr</a></li>
                                                        <li><a href="#">Bing</a></li>
                                                        <li><a href="#">Youtube</a></li>
                                                        <li><a href="#">Facebook</a></li>
                                                    </ul>-->
                    </div>
                    <div class ="center_content">
                        <div class="center_title_bar">Latest products</div>
                        <section>
                            <?php echo $this->layout()->content; ?>
                        </section>
                    </div>
                    <!--</article>-->
                <footer>
                    <div class="row">
                        <div class="span4">
                            <h4 class="muted text-center">Về Đối tác</h4>
                            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                            <a href="#" class="btn"><i class="icon-user"></i> Khách hàng của chúng tôi</a>
                        </div>
                        <div class="span4">
                            <h4 class="muted text-center">Về Đội ngũ</h4>
                            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                            <a href="#" class="btn btn-success"><i class="icon-star icon-white"></i> Đội ngũ của chúng tôi</a>
                        </div>
                        <div class="span4">
                            <h4 class="muted text-center">Về Giải Thưởng</h4>
                            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
                            <a href="#" class="btn btn-info">Liên hệ với chúng tôi</a>
                        </div>


                    </div>
                    <hr>
                    <div class="footer text-left">
                        <h1>Nhóm 08</h1>
                    </div>
                </footer>
        </div>
        <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
        <script src=<?php echo $this->baseUrl() . "/"; ?>js/bootstrap.js></script>
        <script src=<?php echo $this->baseUrl() . "/"; ?>js/bootstrap-hover-dropdown.js></script>
    </body> 
</html>