<!DOCTYPE html>
<html>
    <head>
        <title>Đồ án cuối kì</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/centercontent.css>
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/detail.css>
    </head>
    <body style="">
        <div class="container">
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <ul class="nav">
                            <div class="btn-group">
                                <button class="btn dropdown-menu" onclick="location.href =<?php echo $this->baseUrl() . "/"; ?>;" style="font-weight: bold;"><i class="icon-home"></i> Trang chủ <span ></span></button>
                            </div>
                            <div class="btn-group">
                                <a data-toggle="dropdown" data-hover="dropdown" class="btn dropdown-toggle" style="font-weight: bold;"><i class="icon-ok"></i> Giới thiệu <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->baseUrl() . "/about" ?>">Về đề tài</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>contact">Về nhóm 08</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Về môn học</a></li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <a  data-hover="dropdown" class="btn dropdown-toggle" style="font-weight: bold;"><i class="icon-gift "></i> Sản Phẩm <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>thiep">Thiệp</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>lich">Lịch</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>catalogue">Catalogue</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>namecard">Name card</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>toroi">Tờ rơi</a></li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <a class="btn" href ="<?php echo $this->baseUrl() . "/otherservices" ?>" style="font-weight: bold;"><i class="icon-list"></i> Dịch vụ khác</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn" href ="<?php echo $this->baseUrl() . "/contact" ?>" style="font-weight: bold;"><i class="icon-user"></i> Liên hệ </a>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="navbar-inner">
                <article class="row">
                    <section class="span22">
                        <ul class="nav nav-list bg-list">
                            <li class="nav-header bg-menu-title" align="center"><h6 style="color: black;">Số lượt truy cập</h6></li>
                            <li align="center"><h1><img src="http://cc.amazingcounters.com/counter.php?i=3153335&c=9460318"></h1></li>
                            <li class="nav-header bg-menu-title" align="center"><h6 style="color: black;">Danh mục sản phẩm</h6></li>
                            <li><a href="<?php echo $this->baseUrl() . "/"; ?>thiep"> Thiệp</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/"; ?>lich"> Lịch</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/"; ?>catalogue"> Catalogue</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/"; ?>namecard"> Name card</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/"; ?>toroi"> Tờ rơi</a></li>
                            <li class="nav-header bg-menu-title" align="center"><h6 style="color: black;">Hỗ trợ trực tuyến!</h6></li>
                            <li>
                                <a href="ymsgr:sendIM?yeuem1000nam_1991">Lê Phước Thạch</a>
                                <a href="ymsgr:sendIM?yeuem1000nam_1991">
                                    <img src="http://opi.yahoo.com/online?u=yeuem1000nam_1991&t=14">
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="ymsgr:sendIM?visaoemoi_03tk">Nguyễn Văn Chiến</a>
                                <a href="ymsgr:sendIM?visaoemoi_03tk">
                                    <img src="http://opi.yahoo.com/online?u=visaoemoi_03tk&t=14">
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="ymsgr:sendIM?kimcuongcatkimcuong_12">Lâm Văn Quốc Huy</a>
                                <a href="ymsgr:sendIM?kimcuongcatkimcuong_12">
                                    <img src="http://opi.yahoo.com/online?u=kimcuongcatkimcuong_12&t=14">
                                </a>
                            </li>
                        </ul>
                    </section>
                    <section class="span8">
                        <div>
                            <?php
                            foreach ($this->data as $thiep) {
                                ?>    
                                <!-- Product -->

                                <!---->
                                <div class="item_product">
                                    <div class="images"><a href="#"><img src="<?php echo $this->baseUrl() . "/"; ?>upload/image/<?php echo $thiep['hinhanh']; ?>" border="0"></a></div>  
                                    <div style="height:10px; width:100%;"></div>
                                    <div class="name"><a href="<?php echo $this->baseUrl('/thiep/detail?ctsp&id=' . $thiep['id'])
                                ?>"><?php echo $thiep['tensanpham']; ?></a></div>       
                                </div>
                                <?php
                            }
                            ?>
                        </div>
                        <section class="span8">
                            <div align = "center">
                                <?php
                                echo $this->paginationControl($this->data, 'Sliding', 'paginator.phtml');
                                ?>
                            </div>
                        </section>
                    </section>
                </article>
            </div>
            <hr>
        </div>
    </body>
</html>