<html>
    <head>
        <title>Đồ án cuối kì</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/detail.css>
        <link rel="stylesheet" href=<?php echo $this->baseUrl() . "/"; ?>css/centercontent.css>
    </head>
    <body style="">
        <div class="container">
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <ul class="nav">
                            <div class="btn-group">
                                <a class="btn dropdown-menu" href ="<?php echo $this->baseUrl() . "/" ?>" style="font-weight: bold;"><i class="icon-home"></i> Trang chủ <span ></span></a>
                            </div>
                            <div class="btn-group">
                                <a data-toggle="dropdown" data-hover="dropdown" class="btn dropdown-toggle" style="font-weight: bold;"><i class="icon-ok"></i> Giới thiệu <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->baseUrl() . "/about" ?>">Về đề tài</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>contact">Về nhóm 08</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Về môn học</a></li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <a  data-hover="dropdown" class="btn dropdown-toggle" style="font-weight: bold;"><i class="icon-gift "></i> Sản Phẩm <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>thiep">Thiệp</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>lich">Lịch</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>catalogue">Catalogue</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>namecard">Name card</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->baseUrl() . "/"; ?>toroi">Tờ rơi</a></li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <a class="btn" href ="<?php echo $this->baseUrl() . "/otherservices" ?>" style="font-weight: bold;"><i class="icon-list"></i> Dịch vụ khác</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn" href ="<?php echo $this->baseUrl() . "/contact" ?>" style="font-weight: bold;"><i class="icon-user"></i> Liên hệ </a>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="navbar-inner">
                <article class="row">
                    <section class="span22">
                        <ul class="nav nav-list bg-list">
                            <li class="nav-header bg-menu-title" align="center"><h6 style="color: black;">Quản lý sản phẩm</h6></li>
                            <li><a href="<?php echo $this->baseUrl() . "/admin/"; ?>thiep">Thiệp</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/admin/"; ?>lich">Lịch</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/admin/"; ?>catalogue">Catalogue</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/admin/"; ?>namecard">Name card</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl() . "/admin/"; ?>toroi">Tờ rơi</a></li>
                            <li class="nav-header bg-menu-title" align="center"><h6 style="color: black;">Hình ảnh!</h6></li>
                            <li><a href="<?php echo $this->baseUrl() . "/admin/"; ?>upload">Upload ảnh</a></li>
                            <li class="divider"></li>
                        </ul>
                    </section>
                    <section class="span8">
                        <div class="center_title_bar">Latest products</div>
                        <div class="item_product">
                            <div class="images"><a href="#"><img src="<?php echo $this->baseUrl() . "/"; ?>upload/image/<?php echo $this->detail['hinhanh']; ?>" border="0"></a></div>  
                            <div style="height:10px; width:100%;"></div>
                            <div class="name"><a href=""><?php echo $this->detail['tensanpham']; ?></a></div>       
                        </div> 
                        <ul class="product_info">
                            <li><span><?php echo $this->detail['tensanpham']; ?></span></li>  
                            <li><b>Mã sản phẩm:</b> <?php echo $this->detail['masanpham']; ?></span></li>              
                            <li><b>Giá bán: <span style="color:#F00; font-size:14px;"><?php echo $this->detail['gia']; ?></span></b></li>                
                            <li><b>Lượt xem:</b> 85</span></li>                                            
                        </ul> 
                        <div class ="product_detail">
                            <div class="center_title_bar">Latest products</div>
                            <p><img src="<?php echo $this->baseUrl() . "/"; ?>upload/image/<?php echo $this->detail['hinhanh']; ?>" alt="" width="700" height="486" /></p>  
                        </div>
                    </section>
                </article>
            </div>
        </div>
    </body>
</html>