<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body style="">
        <div class="container">          
            <article class="row">
                <section class="span8">
                    <h3 align="center">CNWeb&UD - SE322.E12 - NHÓM 08</h3>
                    <br>
                    <h6 align="center">(Chưa có)</h6>
                </section>
            </article>
        </div>

    </body>
</html>